Makefile, rdef, fix build, README
HaikuArchives/ZooKeeper pull request #1
Opened 2018-11-10 19:07 UTC by bach5000

A necessary upstream patch for a recipe :)

2018-11-11 08:12 UTC, humdingerb requested changes
A few more things:
* Remove the file "DropZookeeperHere".
* Add "How to install" section in the ReadMe in line 14, saying to copy the addon to `~/config/non-packaged/add-ons/Tracker`.
* In the ReadMe "Example", change the path to `~/config/non-packaged/bin/psviewer`.
* In the ReadMe change the "BeOS" in the last line to "Haiku"

2018-11-11 08:12 UTC, humdingerb commented on Source/ZooKeeper.rdef
> +resource file_types message {
Please move this on top of the icon resource.

2018-11-11 08:12 UTC, humdingerb commented on Source/ZKApp.cpp
> +#include <storage/FindDirectory.h>
Are you 100% sure that's needed?
While you're at it, quickl alphabetically sort the includes.

2018-11-11 08:12 UTC, humdingerb commented on Source/ZKApp.cpp
> +	if (find_directory(B_SYSTEM_TEMP_DIRECTORY, &p) != B_OK)	return B_ERROR;
While you're updating constants, can you correct the path to Terminal in this file, line 368? It's "`/boot/system/apps/Terminal -t`"

2018-11-11 08:12 UTC, humdingerb commented on Source/ZooKeeper.rdef
> +	short_info = "ZooKeeper",
Change to "Tracker add-on to execute scripts", or something...

2018-11-11 08:12 UTC, humdingerb commented on Source/ZooKeeper.rdef
> +	long_info = "ZooKeeper"
Change to "ZooKeeper executes scripts on a set of files", or something...

2018-11-13 19:47 UTC, scottmc commented
Any chance you can wrap this one up today?  You've got a few pending pull requests...  Maybe we need to make sure they are closed before accepting your tasks as complete?

2018-11-14 00:20 UTC, bach5000 commented
@scottmc Oops, sorry! Forgot about this one :)

2018-11-14 00:34 UTC, bach5000 commented
@humdingerb @scottmc Done!

2018-11-14 01:44 UTC, bach5000 commented
@scottmc I'm really sorry for forgetting about this (and perhaps several other tasks) I'll keep in mind to recheck old pull requests as I do my new task... sometimes I get too absorbed in a new task and forget about them 😄
Thanks for the reminder.

2018-11-14 15:23 UTC, humdingerb approved these changes

2018-11-14 15:24 UTC, merged

2018-11-14 15:24 UTC, humdingerb commented
Thanks!